services:
  - type: web
    name: react-construction-site
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
